project:
  type: book
  output-dir: docs
lang: fi
bibliography: references.bib
number-sections: true
editor: visual  
execute:
  echo: false
  warning: false

book:
  title: "Osallisuus- ja vuorovaikutussuunnitelma"
  subtitle: "{{< var version >}}"
  author: "{{< var author >}}"
  page-navigation: true
  cover-image: themes/mukaantoimintaan180-681x490.jpg
  site-url: https://kangasalakehitys.github.io/osallisuus/
  repo-url: https://github.com/Kangasalakehitys/osallisuus/
  repo-branch: master
  repo-actions: [edit]
  sharing: [twitter, facebook, linkedin]
  search: false
  sidebar:
    logo: themes/Kangasala_logo_RGB_color.png
    collapse-level: 3
    pinned: false
    tools:
      - icon: twitter
        href: https://twitter.com

  chapters:
    - index.qmd
    - _valmistelu.qmd
    - _tasot.qmd
    - _tieto_osallisuus.qmd
    - _suunnitteluosallisuus.qmd
    - _paatoksenteko_osallisuus.qmd
    - _toimintaosallisuus.qmd
    - _arviointi.qmd
    - _lainsaadanto.qmd
        
  appendices:
    - _lahteet.qmd

format:
  html: 
    theme: themes/mytheme.scss
    cover-image: themes/mukaantoimintaan180-681x490.jpg
    code-link: true
    