project:
  type: book
  output-dir: docs
lang: fi

book:
  title: "Osallisuus- ja vuorovaikutussuunnitelma"
  subtitle: "{{< var version >}}"
  author: "{{< var author >}}"
  page-navigation: true
  cover-image: themes/mukaantoimintaan180-681x490.jpg
  site-url: https://www.kangasala.fi/kaupunki-ja-paatoksenteko/osallistu-ja-vaikuta/
  search: false
  site-path: "/osallisuus/"
  sidebar:
    logo: themes/Kangasala_logo_RGB_color.png
    collapse-level: 3
    pinned: false
    tools:
      - icon: twitter
        href: https://twitter.com

  chapters:
    - index.qmd
    - _valmistelu.qmd
    - _tasot.qmd
    - _tieto_osallisuus.qmd
    - _suunnitteluosallisuus.qmd
    - _paatoksenteko_osallisuus.qmd
    - _toimintaosallisuus.qmd
    - _arviointi.qmd
    - _lainsaadanto.qmd
        
  appendices:
    - _lahteet.qmd

format:
  html: 
    theme: themes/mytheme.scss
    callout-appearance: simple

editor: visual  
execute:
  echo: false
  warning: false


bibliography: references.bib
number-sections: true