# Osallisuuden arviointi ja mittaaminen

Osallisuutta voidaan arvioida yksilön ja organisaation tasolla. Kuinka eri toiminnot ja palvelut edistävät osallisuutta? Osallisuuden arviointi edistää toiminnan kehittämistä. Lisäksi arviointi auttaa suunnittelemaan resurssointia osallisuustyöhön. On tärkeää nähdä kokonaisuus eli mitä kaikkea osallisuus pitää sisällään.  (mukaillen: Kurikka P. & Piipponen S-L, s.4 2020, Opas kuntalaisten osallistumisen arviointiin) 

Osallisuuden arvioinnissa on hyödynnetty kuntakohtaisiaa vertailutietoja, joita tuottaa esimerkiksi Terveyden ja hyvinvoinnin laitos (THL). THL ylläpitää esimerkiksi TEAviisaria, joka kattaa kuusi eri tietokokonaisuutta: kuntajohdon, perusopetuksen, lukion, ammatillisen koulutuksen, perusterveydenhuollon, liikunnan ja kulttuurin. Tietokokonaisuudet koostetaan kuudesta ulottuvuudesta, joista yksi on osallisuus. 

Kuntakohtainen vertailutieto mittaa yleensä osallisuutta siten, onko jotakin tehty (Kyllä) tai ei ole tehty (Ei). Esimerkkejä:

-   kunta on järjestänyt keskustelutilaisuuden

-   kunta on tehnyt asiakas-/käyttäjäkyselyn

-   kunnalla on keskustelupalsta internetissä, somessa tms.

Kunnat ovat hyödyntäneet osallisuuden arvioinnissa esimerkiksi seuraavia kriteereitä.

## Kunnan yleiset tavoitteet kuntalaisten osallistumiselle ja vaikuttamiselle

-   Osallisuusohjelman tai suunnitelman laatiminen

-   Osallisuus strategiassa

-   Osallisuus kaupungin budjetissa huomioituna

-   Osallisuuden laaja edistäminen

-   Osallisuuskoordinattorin työ

## Koulutus

-   Henkilöstökoulutus/ -valmennus osallisuuden edistämisestä

-   Kuntademokratiaverkosto

-   Osallisuuspeli

-   Erätauko
