# Esipuhe {.unnumbered}

Luet Kangasalan kaupungin osallisuus- ja vuorovaikutussuunnitelmaa. Suunnitelmasta löydät osallisuuden pelikentän Kangasalla, sekä huomaat miten eri tavoin voit osallistua osallisuustyöhön. Suunnitelman tarkoituksena on antaa uusia vinkkejä ja kuvata osallisuuden eri toimintamuotoja.

Osallisuudella tarkoitetaan ihmisten kokemaa kuulumista yhteiskuntaan, yhteisöihin ja elämistä itselle sopivalla tavalla. Osallisuutta kokeva tulee kuulluksi ja edistää tärkeäksi kokemiaan asioita. Osallistumisoikeus yhteiskunnan ja oman ympäristönsä kehittämiseen määritellään perustuslaissa. Kuntalaisten osallisuuden edistäminen on osa demokratiaa. Kunta tarjoaa osallistumismahdollisuuksia, tukee omaehtoista toimintaa ja hyödyntää kehityksessä kuntalaisten ja yhteisöjen osaamista. [mukaillen: @kurikka_piipponen_2020]

Kangasalan kaupungin osallisuus- ja vuorovaikutussuunnitelmaan on koottu nykyisiä osallisuuden muotoja ja toimintatapoja. Suunnitelman tarkoituksena on antaa vinkkejä osallisuuden eri muodoista ja kannustaa aktiiviseen osallisuuteen kaupungissa. Tarkoituksena on hyödyntää kuntalaisten ja yhteisöjen osaamista ja asiantuntemusta palveluiden kehittämisessä. Suunnitelma toimii kaupungin asukkaiden, työntekijöiden ja päätöksentekijöiden työkalupakkina. Osallisuus on myös tunne, joka yksilölle muodostuu yhdessä tekemisestä tai kuulumisesta tiettyyn yhteisöön. Osallisuudessa olemme osa ympäröivää yhteiskuntaa ja yhteisöä. Osallisuuden tulee kattaa kaupungin koko toiminta ja osallisuus on kirjattu myös kaupungin [strategiaan @sec-strategia].

Erilaisia kuntalaisen osallistamisen muotoja voidaan luokitella seuraavan jaon mukaan: tieto-, suunnittelu-, päätöksenteko-, ja toimintaosallisuus. Kunnan on hyvä tarjota monenlaisia osallistamisen tapoja ja muotoja. Kangasalan kaupungin osallisuussuunnitelman viitekehyksenä toimii jako tieto-, suunnittelu-, ja päätöksenteko ja toimintaosallisuus.
