# Päätösosallisuus

Päätösosallisuudessa kuntalainen osallistuu suoraan palvelujen tuottamista tai asuinaluettaan koskeviin päätöksiin. Nuorisovaltuuston edustajat ovat mukana kaupunginvaltuustossa ja lautakunnissa.

## Aloite

Kuntalain mukaan asukkaalla sekä alueella toimivalla yhteisöllä ja säätiöllä on oikeus tehdä aloitteita kunnan toimintaa koskevissa asioissa. Kirjallisen aloitteen voi tehdä sähköisen aloitesivuston kautta [kuntalaisaloite.fi](https://www.kuntalaisaloite.fi/fi) tai toimittamalla kirjallisen aloitteen kaupungin kirjaamoon.

## Kansanäänestys ja äänestäminen

Kaupunginvaltuusto voi päättää, että kaupungille kuuluvasta asiasta toimitetaan kaupungin alueella neuvoa-antava kansanäänestys. Äänestysoikeus määräytyy samoin kuin äänioikeus kuntavaaleissa. Tulos on neuvoa-antava.

Äänestäminen on osallistumista ja vaikuttamista. Kuntavaalit pidetään neljän vuoden välein. Kunta- ja muiden vaalien yhteydessä kouluissa järjestetään varjovaaleja.  Osassa kouluista toimii oppilaskunta ja niissä on järjestetty oppilaskuntavaaleja.

## Kaupungin vaikuttamistoimielimet

Kaupunginhallitus asettaa vaikuttamistoimielimet. Kangasalla on toiminnassa seuraavat vaikuttamistoimielimet:

        -   Nuorisovaltuusto

        -   Vammaisneuvosto

        -   Vanhusneuvosto

    -   Ei lakisääteisiä:

        -   Kausiasukkaiden viestintäryhmä 

        -   Seuraparlamentti (liikuntapalvelut) 

## Kaupungin viralliset toimielimet

-   Valtuusto
-   Kaupuginhallitus
-   Lautakunnat
    -   [Keskusvaalilautakunta](https://www.kangasala.fi/kaupunki-ja-paatoksenteko/paatoksenteko/toimielimet/lautakunnat/keskusvaalilautakunta/)
    -   [Elinympäristölautakunta](https://www.kangasala.fi/kaupunki-ja-paatoksenteko/paatoksenteko/toimielimet/lautakunnat/elinvoimalautakunta/)
    -   [Sivistyslautakunta](https://www.kangasala.fi/kaupunki-ja-paatoksenteko/paatoksenteko/toimielimet/lautakunnat/sivistyslautakunta/)
    -   [Hyvinvointilautakunta](https://www.kangasala.fi/kaupunki-ja-paatoksenteko/paatoksenteko/toimielimet/lautakunnat/hyvinvointilautakunta/)
    -   [Viranomaislautakunta](https://www.kangasala.fi/kaupunki-ja-paatoksenteko/paatoksenteko/toimielimet/lautakunnat/viranomaislautakunta/)
    -   [Tarkastuslautakunta](https://www.kangasala.fi/kaupunki-ja-paatoksenteko/paatoksenteko/toimielimet/lautakunnat/tarkastuslautakunta/)
    -   [Kangasalan Vesi -liikelaitoksen johtokunta](https://www.kangasala.fi/kaupunki-ja-paatoksenteko/paatoksenteko/toimielimet/lautakunnat/kangasalan-vesi-liikelaitoksen-johtokunta/)

## Viralliset lausunnot, mielipiteet, muistutukset ja valitukset

Kangasalan kaupunki ilmoittaa julkisilla kuulutuksilla mahdollisuuksista ja oikeuksista mielipiteiden ja muistutusten jättämiseen.  Lausuntoja voidaan pyytää kuulutuksilla tai erikseen niin kaupunkiorganisaation sisältä kuin myös muilta asianosaisilta tahoilta, joita kulloinenkin aihe koskee. Lausuntoja pyydetään myös lakisääteisiltä vaikuttamistoimielimiltä. Päätöksistä on lainsäädännön puitteissa mahdollista valittaa. Lausunnot ja muut viralliset kannanotot otetaan huomioon päätöksenteossa.

Esimerkkinä ulkoalueiden hankkeiden suunnitelmat asetetaan yleisesti nähtäville ja suunnitelmista on mahdollisuus jättää palautetta. Kaikki palautteet käsitellään ja niihin vastataan hankkeen suuruudesta riippuen viranhaltijapäätöksessä tai elinympäristölautakunnan päätöksessä, joka lähetetään kaikille palautteen jättäjille.

## Muutoksenhaku

Muutoksenhaku on yksi vaikuttamiskeino. Muutoksenhaun kohteena voivat yleensä olla kaupungin viranomaisen lopulliset päätökset. Valmistelua tai täytäntöönpanoa koskeviin päätöksiin ei voi hakea muutosta.Muutoksenhaun, kuten oikaisuvaatimuksen tai valituksen, kohteena voivat yleensä olla kaupungin viranomaisen lopulliset päätökset.
