# Suunnitteluosallisuus

Suunnitteluosallisuudessa kuntalainen on mukana kaupungin ja kuntalaisen välisessä suunnittelussa ja valmistelussa. Tästä esimerkkinä osallistuminen palvelukehitykseen ja yhteissuunnitteluun. Kuntalaiset voivat osallistua esimerkiksi itseään koskevan toiminnan, palvelun tai elinympäristön suunnitteluun kertomalla ideoitaan ja mielipiteitään.

## Asiakasraadit

Ateria- ja siivouspalveluilla on käytössä Kangasalla kouluruokaraati. Kouluruokaraatiin pyydetään edustajat kouluista ja nuorisovaltuustosta. Kouluruokaraadissa maistellaan ja arvioidaan uusia listalle tulevia ruokavaihtoehtoja, käydään läpi palautteita ja arvioidaan kouluruokailua. Kouluruokaraati on perustettu Nuorisovaltuuston aloitteesta 2017.

## Asukas- ja infotilaisuudet sekä vuorovaikutteiset työpajat

Kuntalaisten on mahdollista osallistua itseään koskevan kaupungin suunnitteluhankkeen yhteydessä järjestettäviin tilaisuuksiin. Esimerkiksi liikuntapaikkarakentamisen tai kaavoituksen yhteydessä voidaan järjestää asukas- ja yleisötilaisuuksia.

Lue lisää tapahtumista [tapahtumakalenterista](https://www.kangasala.fi/kaupunki-ja-paatoksenteko/osallistu-ja-vaikuta/tilaisuudet-ja-tapahtumat/)

## Vaikutusten ennakkoarvioinnit

Kuntahallinnossa tehtävät päätökset ovat usein mittavia ja laajoja, ja ne vaikuttavat merkittävästi kuntalaisiin ja kunnan talouteen. Vaikutusten ennakkoarvioinnilla tarkoitetaan päätösesitysten vaikutusten arviointia etukäteen ja se tulee kytkeä osaksi kunnan talouden ja toiminnan suunnittelun ja toteutuksen arviointiin.

Valmistelijan tai esittelijän vastuulla on yleensä päättää ennakkovaikutusten arvioinnin tekemisestä valmisteilla olevasta asiasta sekä myös tarkasteltavien päätösvaihtoehtojen määrästä. Arvioitavat asiat liittyvät strategiaan, asiakkaisiin ja asukkaisiin sekä vapaa-ajanasukkaisiin, lapsiin ja perheisiin, henkilöstöön ja talouteen sekä ympäristöön. [Yritysvaikutusten arviointia](https://link.webropol.com/s/yritysvaikutukset) tehdään omalla arviointikokonaisuudellaan mobiilisti

Kangasalla lapsivaikutusten arviointi on tärkeä osa Unicefin Lapsiystävällinen kunta työtä. Vaikutusten ennakkoarviointia (EVA) tehdään kokonaisuudessaan Kangasalla [mobiililomakkeen](https://link.webropol.com/s/evalomake) kautta.

Kaavoituksen yhteydessä vaikutusten arviointia tehdään eri näkökulmista. Kaavahankkeisiin liittyvä lakisääteinen vaikutusten arviointi kuvataan kaavaselosteissa. Vaikutusten ennakkoarviointia on tehty mm. kouluverkkopäätösten yhteydessä laajasti. Arviointiin ovat päässeet osallistumaan sekä lapset ja nuoret, huoltajat, päättäjät että muut kuntalaiset. Arviointimenetelmiä ovat olleet mm. kyselyt, kuulemistilaisuudet ja ryhmätyöt.

## Kokemusasintuntijoiden käyttö palvelukehityksessä

Lasten ja nuorten hyvinvointiryhmässä ja perhekeskustyöryhmässä on mukana Kangasalan vanhemmat ry:n ja nuorisovaltuuston edustaja. Lisäksi kaikissa Kangasalan kaupungin hyvinvointityön ryhmissä on mukana kuntalaisedustajia muun muassa paikallisista järjestöistä ja yhdistyksistä. Hyvinvointityön työryhmissä on myös mukana kuntalaisedustajia, jotka edustavat Kangasalalla toimivia järjestöjä tai Kangasalan yrittäjiä.

## Lasten ja nuorten vaikuttamistapahtumat

Kangasalan nuorisovaltuusto järjestää lasten ja nuorten vaikuttamistapahtumia. Vuoro vuosittain pidetään Lasten kyselytunti alakouluikäisille ja SAP -Sullon Asiaa Päättäjille tapahtuma yläkouluikäisille. Näissä tapahtumissa lapset ja nuoret pääsevät samaan pöytään keskustelemaan kaupungin valtuutettujen ja viranhaltijoiden kanssa.    

Kaupunginvaltuusto ja nuorisovaltuusto tekevät yhteistyötä mm. nimeämällä kummivaltuutettuja ja pitämällä yhteisiä iltakouluja 2 krt vuodessa (2022 alkaen).

## Luottamushenkilöiden keskustelutilaisuudet

Johtavat kunnallispoliitikot jalkautuvat asukasiltoihin noin neljä kertaa vuodessa eri puolille kaupunkia. Lue lisää tapahtumista [tapahtumakalenterista](https://www.kangasala.fi/kaupunki-ja-paatoksenteko/osallistu-ja-vaikuta/tilaisuudet-ja-tapahtumat/)

## Osallistuva budjetointi

Osallistuva budjetointi on toimintatapa, jossa asukkaat otetaan mukaan yhteisiä verovaroja koskevaan keskusteluun, suunnitteluun ja päätöksentekoon.

Kangasalla järestetään vuosittain sähköinen verkkokysely ja kyselyn pohjalta valikoituu toteutettavat tapahtumat ja kohteet/hankkeet. Poikkihallinnollinen Liiku ja leiki-työryhmä toteuttaa osan osallistuvan budjetoinnin hankkeista.

## Vapaa-ajanasukkaiden foorumi {#sec-vapaa_aika_foorumi}

Kangasalla järjestetään vapaa-ajanasukkaiden ja kaupunginjohtajan infotilaisuuksia, joissa viestitään uusimmista kaupungin tapahtumista kaupungissa ja kuullaan vapaa-ajanasukkaiden kehitystarpeita.

## Lakisääteinen vuorovaikutus

Kaavahankkeiden osallistamisen ja tiedottamisen tavat kuvataan kussakin kaavahanketta koskevassa osallistumis- ja arviointisuunnitelmassa.

Maankäyttö- ja rakennusasetuksen edellyttämä yleinen vuorovaikutus katusuunnitelmaa valmisteltaessa hoidetaan asukaskirjeellä. Asukaskirjeessä ilmoitetaan katusuunnitelman nähtävillä olosta, kerrotaan katusuunnitelmaehdotuksen taustat, suunnitelman sisältö ja toteutusaikataulu. Vuorovaikutusvaiheessa osalliset voivat jättää mielipiteensä kirjallisesti tai suullisesti. 
