# Tieto-osallisuus

Kuntalaisilla on oikeus tiedon saamiseen ja tuottamiseen. Tähän osallisuuteen liittyy esimerkiksi viestintä, kuuleminen ja vastaaminen kyselyihin.

## Aloite

Kuntalain mukaan asukkaalla sekä alueella toimivalla yhteisöllä ja säätiöllä on oikeus tehdä aloitteita kunnan toimintaa koskevissa asioissa. Kirjallisen aloitteen voi tehdä sähköisen aloitesivuston kautta [kuntalaisaloite.fi](https://www.kuntalaisaloite.fi/fi) tai toimittamalla kirjallisen aloitteen kaupungin kirjaamoon.

## Asukas- ja info-tilaisuudet

Kaupunki ja sen toimijat järjestävät asukkaille ja eri toimijoille avoimia tilaisuuksia. Keskustelutilaisuudet tarjoavat asukkaille tilaisuuden kertoa mielipiteistään asiantuntijoille ja päättäjille. Onnistunut tilaisuus synnyttää vuoropuhelua ja tuloksellista dialogia.

Kaupunginjohtaja on Kangasalan asukkaiden tavattavissa säännöllisesti kaupungin infopisteellä Lentolan Prismassa. Asukastilaisuuksien tarkemmista ajankohdista informoidaan hyvissä ajoin eri kanavissa kuntalaisten saavuttamiseksi. Asukastilaisuuksia järjestetään kaksi kertaa vuodessa, sekä keväällä että syksyllä. Tilaisuudet ovat vapaamuotoisia keskustelutilaisuuksia, jossa asukkailla on mahdollisuus päästä keskustelemaan mistä vain mieltä askarruttavasta asiasta ilman ennakkoilmoittautumista.

Kangasalla järjestetään uusien asukkaiden tilaisuus vuosittain kulttuuri- ja hyvinvointitorin yhteydessä. Palvelukeskukset on järjestäneet Kangasalla streamattuja tilaisuuksia, joissa kuntalaiset ovat voineet etukäteen tai tilaisuudessa esittää kysymyksiä.

## Avoimet ovet

Kulttuuripalvelut järjestävät Kangasalla kerran vuodessa museoihin ja gallerioihin vapaan pääsyn. Varhaiskasvatuksessa, opetuksessa ja koulutuksessa järjestetään mm. läheisenpäiviä, kodin ja päiväkodin/koulun päiviä ja erilaisia muita teemapäiviä, joihin huoltajat ja myös esim. isovanhemmat ovat tervetulleita.

Nuorisopalvelut järjestävät tarpeen mukaan huoltajille suunnattuja avoimia ovia ja huoltajien keskusteluiltoja nuorisotiloilla.Kulttuuripalvelut järjestävät Kangasalla kerran vuodessa museoihin ja gallerioihin vapaan pääsyn.

## Esityslistat, pöytäkirjat ja viranhaltijapäätökset

Kaupungin luottamustoimielinten esityslistat ja pöytäkirjat löytyvät kaupungin verkkosivuilta [Esityslistat ja pöytäkirjat sekä viranhaltijapäätökset 1.1.2019 alkaen](http://kangasala.tweb.fi/ktwebbin/dbisa.dll/ktwebscr/epj_tek_tweb.htm)

## Info asukkaiden palautteiden ja aloitteiden huomioimisesta

Palautteen antajalle ja aloitteen tekijälle vahvistetaan, miten hänen antamansa palaute tai aloite on otettu huomioon asioiden suunnittelussa ja päätöksenteossa. Jos palautetta tai aloitetta ei ole voitu ottaa huomioon, niin perustellaan huomioimatta jättäminen.

## Kangasalan kaupunki-info

Kangasalan kaupunki-info palvelee Lentolan Prismassa tiistaista lauantaihin. Puhelin infoon on 044 481 3022.

## Kaupungin kirjaamo - virallinen yhteydenotto

Kaupungin asukas voi tehdä kaupungin hallinnolle virallisen yhteydenoton joko sähköpostiosoitteeseen kirjaamo\@kangasala.fi tai toimittamalla yhteydenotto kaupungin kirjaamoon. Virallista yhteydenottoa ei voi tehdä nimettömänä.

## Palautekanavat

-   [Anna palautetta ja vastaa kyselyihin Kangasalla - Kangasala.fi](https://www.kangasala.fi/kaupunki-ja-paatoksenteko/osallistu-ja-vaikuta/anna-palautetta-ja-vastaa-kyselyihin)

### Ateria- ja siivouspalvelu

-   Jamix Menu palautekanava. Toimii ruokalista-sovelluksen kautta.

### Infrapalaute

-   [Katuinfraa, kunnossapitoa, valaistusta, puistoja, uimarantoja, leikkialueita ja liikennettä koskevat palautteet](https://louhi-kangasala.sitowise.com/palaute)

### Kaupungin yleinen palautekanava

-   [Kaupungin palautekanava](https://q.surveypal.com/PALAUTTEET/0)

### Kangasalan kuntalaisaloite

-   [Kangasalan kuntalaisaloite](https://q.surveypal.com/Kuntalaisaloite---kopio/0)

    -   Tällä hetkellä palvelu vaatii vahvan tunnistautumisen. 

-   Lähetetään sähköpostiosoitteeseen kirjaamo\@kangasala.fi

### Kulttuuripalveluiden palautelomake

-   [Kulttuuripalveluiden palautelomake](https://www.kangasala.fi/hyvinvointi-ja-vapaa-aika/kulttuuri/palaute/)

### Kirjastopalveluiden palautelomake

-   [Kirjastopalveluiden palautelomake](https://www.kangasala.fi/hyvinvointi-ja-vapaa-aika/kirjasto/palaute/)
-   [Kirjastopalveluiden hankintaehdotuslomake](https://www.kangasala.fi/hyvinvointi-ja-vapaa-aika/kirjasto/palvelut/kokoelmat-ja-tiedonhaku/tee-hankintaehdotus/)

### Liikuntapalveluiden palautelomake

-   [Liikuntapalveluiden palautelomake](https://www.kangasala.fi/hyvinvointi-ja-vapaa-aika/liikuntapalvelut/palautelomake/)

### Nuorisopalveluiden palautelomake

-   [Nuorisopalveluiden palautelomake](https://www.kangasala.fi/hyvinvointi-ja-vapaa-aika/nuorisopalvelut/palautelomake/)

### Nuorisopalveluiden Pyydä apua-nappi, Pyydä apua! - Kangasala

-   [Pyydä apua-nappi](https://q.surveypal.com/Pyyda-apua!/0)

### Sähköinen perhekeskus

-   [Sähköinen perhekeskus](https://q.surveypal.com/Sahkoinen-perhekeskus/0)

    Palvelupalaute 

    -   Pääkirjasto, kulttuuripalvelut (kierrätettävä)

    -   Ateria- ja siivoupalalvelut 3 x HappyOrNot laitetta (kiertäviä laitteita)

### Kangasalan Vesi -liikelaitoksen palautekanava

-   [Kangasalan Vesi -liikelaitoksen palautekanava](https://www.kangasalanvesi.fi/palaute/)

### Kangasalan uimahalli - palautekanava

-   [Kangasalan uimahalli - palautekanava](https://kangasalanuimahalli.fi/ota-yhteytta/palaute/)

### Kangasala-talo - palautekanava

-   [Kangasala-talo - palautekanava](https://kangasala-talo.fi/kangasala-talo/anna-palautetta/)

### Ateria- ja siivoupalvelut

-   3 x kosketusnäyttökanava (kiertäviä laitteita)

## Ministeriöiden palautekanavat

Otakantaa.fi ja Kuntalaisaloite.fi ovat oikeusministeriön ylläpitämiä ja tuottamia verkkopalveluja.

-   [Otakantaa.fi - Oikeusministeriö](https://www.otakantaa.fi/fi/)

-   [Kuntalaisaloite.fi - Oikeusministeriö](https://www.kuntalaisaloite.fi/fi)

## Kokousvideoinnit

Kangasalan Sanomat videoi kaupunginvaltuuston kokoukset. Tallenteet löytyvät [Kangasalan Sanomien verkkosivuilta](https://kangasalansanomat.fi/videot/valtuusto).

## Kyselyt päätöksenteon tueksi ja toiminnan kehittämiseksi

Kaupunki toteuttaa monipuolisin viestintätavoin toteutettuja kyselyitä asukkaille kaupungin toiminnan

-   Hyvinvointikysely: Ei tällä hetkellä voimassaolevia kyselyitä

-   Kaavoitus- ja aluekehityshankkeisiin liittyvät kyselyt

-   Kaupunkikehityskysely: Kaupunkikehitystiimi järjesti syksyllä 2020 kyselyn kaupunkilaisille, jossa pyydettiin kaupunkilaisten näkemyksiä Kangasalan kaupungin nykytilasta ja ajatuksia kaupungin kehittämisestä. **Linkki [Kaupunkikehityskyselyn koosteeseen.](https://www.kangasala.fi/wp-content/uploads/2020/12/Kaupunkikehityskysely-osallistu-ja-vaikuta.pdf)**

-   Kulttuurikasvatuksessa toteutetut kyselyt kouluille

-   Kyselyt oppilaille ja huoltajille: Opetus- ja koulutuspalveluiden tai koulujen omat kyselyt, joista tiedotetaan vastaajia erikseen

-   Kyselyt liikuntapalveluiden käyttäjille oman toiminnan kehittämiseksi.

-   Nuorisopalvelut toteuttavat palautekyselyjä kausittain, joko valtakunnallisella kyselyllä tai omalla Forms-kyselyllä

-   Nuorisovaltuusto toteuttaa kyselyitä ajankohtaisista tai vaikuttamistapahtumiin liittyvistä aiheista sosiaalisessa mediassa, yhteistyössä oppilaskuntien kanssa ja joskus Wilma-viestillä suoraan oppilaille.

-   Osana Unicefin Lapsiystävällinen kunta-työn nykytilakartoitusta lapsia ja nuoria kuullaan heidän kokemuksistaan ja näkemyksistään lasten oikeuksien toteutumisesta Kangasalla sekä kehittämisideoista.

-   Rakentamisen palvelualueen hankkeissa on käytössä sähköiset kyselyt. Kyselyissä ja vastauksissa hyödynnetään kaupungin internet-sivuja ja some-kanavia.

-   Ateria- ja siivouspalvelujen toiveruokakyselyt. Asiakkaat voivat äänestää viikon ruoat ja antaa palautetta ruokalistoilla olevista ruoista.

-   Ulkoalueiden hankkeissa ollut käytössä sähköiset kyselyt. Kyselyt ja vastaukset linkitetty myös Ulkoalueiden omalle sivustolle: Viheralueet ja ulkoliikuntapaikat - Kangasala ja kaupungin some-kanaviin. 

-   Varhaiskasvatuksessa aloittaneiden kysely kaksi kertaa vuodessa sekä varhaiskasvatuksen ja esiopetuksen vuosittainen asiakastyytyväisyyskysely. Lisäksi vuosittain toteutetaan lasten kysely.

## Monikanavainen viestintä

-   Ajankohtaiset uutiset: [Kangasalan kaupunki - ajankohtaista](https://www.kangasala.fi/#news)

-   Facebook:

    -   [Kangasalan kaupunki](https://www.facebook.com/kangasalankaupunki)

    -   [Kangasalan kirjasto](https://www.facebook.com/kangasalankirjasto)

    -   [Liikkuva Kangasala - Kunnon kaupunki](https://www.facebook.com/people/Liikkuva-Kangasala-Kunnon-kaupunki/100051088791620/)

    -   [Kangasalan kulttuuri- ja vapaa-aika - Kunnon kaupunki](https://www.facebook.com/profile.php?id=100077891494417)

    -   [Lasten Kangasala](https://www.facebook.com/lastenkangasala/)

    -   [Kangasalan Nuorisopalvelut](https://www.facebook.com/kangasalan.nuorisotilat/)

    -   [Kangasalan kaupunki-info](https://www.facebook.com/people/Kangasalan-kaupunki-info/100070137012661/)

    -   [Nuorten neliö - kangasalalaisille 16 -- 29 -vuotiaille nuorille tarkoitettu avoin kohtaamispaikka](https://www.facebook.com/nuortennelio/)

-   Infonäytöt

-   Instagram:

    -   [Kangasalan kaupunki](https://www.instagram.com/kangasalankaupunki/)

    -   [Kangasalan kulttuuripalvelut](https://www.instagram.com/kangasalankulttuuripalvelut/)

    -   [Kaupunki-info](https://www.instagram.com/kangasalankaupunki_info/)

    -   [Kirjastopalvelut](https://www.instagram.com/kangasalankirjasto/)

    -   [Nuorisopalvelut](https://www.instagram.com/kangasalannuorisopalvelut/)

    -   [Nuorisotila Sentteri](https://www.instagram.com/sentteri_kangasala/)

    -   Koulujen omat Instagram sivut

    -   Varhaiskasvatus- ja esiopetusyksiköillä omat Instagram-sivut, lisäksi ryhmillä suljetut Instagram-sivut huoltajille

-   [Kaupungin Internet-sivujen chat-palvelu](https://www.kangasala.fi/)

-   [Kangasalan kirjasto palvelee Piki-kirjastojen chatissa](https://www.kangasala.fi/omatuutiset/piki-verkkokirjaston-chat-palvelu/)

-   Kuulutukset ja ilmoitukset: [Kangasalan kaupunki - ajankohtaista](https://www.kangasala.fi/#news)

-   Linkedin:

    -   [Oskari Auvinen - kaupunginjohtaja](https://fi.linkedin.com/in/oskariauvinen)
    -   [Kangasalan kaupunki](https://fi.linkedin.com/company/kangasalan-kaupunki)

-   Perinteiset ilmoitustaulut

-   Puhelinvaihde

-   Snapchat:

    -   Nuorisotilojen snapnimet @klaveturi @klasentteri @klasahku @klaruutis @kylakolli

-   TikTok:

    -   klanuorisojaliikunta (@klanuorisojaliikunta) \| TikTok

-   Videot:

    -   (Dreambroker-kanava): [Kangasala-kanava](https://dreambroker.com/channel/89q2oh3a/#/menu)

    -   Youtube: [Kangasalan kaupunki](https://www.youtube.com/@kangasalankaupunki9294)

-   X:

    -   Kangasalan kirjasto: <https://twitter.com/kangkirjasto>

    -   Kaupunginjohtaja Oskari Auvinen: <https://twitter.com/oskari_auvinen>

    -   Nuorisovaltuusto: <https://twitter.com/nuvakangasala>

## Tilastotietoa Kangasalta

Tilastotietoa Kangasalta on saatavissa useammasta paikasta:

-   [Kangasalan tilastokirjat](https://www.kangasala.fi/kaupunki-ja-paatoksenteko/hallinto-ja-talous/strategiat-talous-ja-tilastot/tilastot-ja-tutkimus/tilastokirjat/)
-   [Kuntaliiton Kuntanavigaattori](https://www.kuntaliitto.fi/tietotuotteet-ja-palvelut/analyysit-ja-tietoaineistot/kuntanavigaattori)
-   [Kuntien avainluvut](https://www.stat.fi/tup/alue/kuntienavainluvut.html)
-   [Kunnat ja kuntayhtymät](https://www.kuntaliitto.fi/kunnat-ja-kuntayhtymat)
-   [SeutuNet: Tampereen kaupunkiseutu](https://tilastokeskus.fi/tup/seutunet/tampere_index.html)
-   [Suomen yleisten kirjastojen tilastot](https://tilastot.kirjastot.fi/)
-   [Tilastotietoa Kangasalta](https://kangasalakehitys.github.io/tilastot/yleistieto/)
-   [Nuorisotyö kunnissa -- Nuorisotilastot.fi](https://nuorisotilastot.fi/1131/visualisoinnit/nuorisotyo-kunnissa/)
