# Toimintaosallisuus

Toimintaosallisuudessa kuntalainen osallistuu toimintaan elinympäristönsä kehittämiseksi, esimerkkinä siivous-, vieraslaji- ja kytkentätalkoot. Kaupunki toimii mahdollistajana ja tukijana monin eri tavoin.

## Asukastoiminta asukas- ja kyläyhdistyksissä

Kangasalla on aktiivista asukas- tai kyläyhdistystoimintaa. [Yhteystiedot löytyvät kaupungin verkkosivuilta.](https://www.kangasala.fi/hyvinvointi-ja-vapaa-aika/yhdistykset-ja-seurat/)

## Kaupungin järjestöyhteistyö

Kangasalan kaupungin järjestöyhteistyön tarkoituksena on edistää järjestöjen ja Kangasalan kaupungin välistä yhteistyötä, helpottaa tiedon löytymistä ja vahvistaa kaupunkilaisten osallisuutta. Järjestöyhteistyö edistää kaupunkilaisten hyvinvointia, helpottaa järjestöjen toimintaa, edistää sujuvaa yhteistyötä sekä lisää yhteistyön avoimuutta. Kaupungin järjestöyhteistyötä tekee järjestöyhteistyön tiimi, jossa on mukana myös paikallisia järjestöjä edustamassa kaksi järjestöagenttia. Kulttuuri- ja hyvinvointitori keväällä vuosittain järjestettävä messutyyppinen tapahtuma, jossa kaupunki tarjoaa kolmannen sektorin toimijoille mahdollisuuden esitellä kuntalaisille omaa toimintaansa. Järjestöyhteistyön puitteissa järjestetään myös muita pienempiä verkostoitumistapahtumia paikallisille järjestöille ja yhdistyksille. Kangasalan maaseutuohjelmaan on kirjattu tavoitteeksi aktiivinen vuoropuhelu kaupungin ja kyläyhdistysten kesken. Järjestöjen toimintaa tuetaan myös avustuksilla ja yhteistyösopimuksilla.

## Asukkaiden omaehtoisen toiminnan tukeminen

Kaupunki tukee asukkaiden omaehtoista toimintaa oman asuinalueen kehittämiseksi ja elävöittämiseksi.

-   [Kulttuuritoiminnan kohde- ja toiminta-avustus](https://suomiviestit.fi/suomi.fi/lomake/60337de0475a6c2cf601e209) Hyvinvointilautakunta myöntää avustuksia yhdistysrekisterissä oleville kangasalalaisille kulttuuriyhdistyksille.

-   [Kulttuuristipendi](https://www.kangasala.fi/hyvinvointi-ja-vapaa-aika/avustukset/kulttuuri/kulttuuristipendit/) oidaan myöntää nuorille, alle 29-vuotiaille kangasalalaisille taiteilijoille tai taiteenalan opiskelijoille hakemuksesta taiteellisten ansioiden perusteella.

-   [Björkqvist-rahaston apurahat ja stipendit](https://www.kangasala.fi/hyvinvointi-ja-vapaa-aika/avustukset/kulttuuri/bjorkqvistin-rahaston-stipendit-ja-apurahat/) Björkqvist-rahastosta myönnetään apurahoja Kangasalan peruskoulusta tai toisen asteen oppilaitoksesta päättötodistuksen saaneiden hakijoiden tieteelliseen tutkimukseen tai taiteelliseen toimintaan. Apuraha voidaan myöntää myös hakijalle, jolla ei ole Kangasalan peruskoulusta tai toisen asteen oppilaitoksesta saatua päättötodistusta, mutta jonka tieteellinen tai taiteellinen työ edistää kaupungin henkistä tai aineellista kulttuuria.

-   [Nuoriso - toiminta-avustus](https://www.kangasala.fi/hyvinvointi-ja-vapaa-aika/avustukset/nuoriso/) Hyvinvointilautakunta avustaa nuorisojärjestöjä ja järjestäytyneitä nuorisoryhmiä vuosiavustuksella.

-   [Liikunta - toiminta-avustus](https://www.kangasala.fi/hyvinvointi-ja-vapaa-aika/avustukset/liikunta/vuosiavustus/) Hyvinvointilautakunta myöntää toiminta-avustuksia yhdistysrekisterissä oleville kangasalalaisille liikunta- ja urheiluseuroille ja yhdistyksille. Toiminta-avustusten hakuaika on vuosittain 1.-31.3.

-   [Liikunta - kohdeavustus](https://www.kangasala.fi/hyvinvointi-ja-vapaa-aika/avustukset/liikunta/kohdeavustus/) Liikunnan kohdeavustukset tulee hakea talven toiminta-ajalta 1.11.-30.4.Kohdeavustusta myönnetään ensisijaisesti yhdistysrekisterissä olevien seurojen valmentaja-, ohjaus ja toimitsijakoulutuksesta aiheutuneisiin kustannuksiin.

-   [Liikunta - Valmennus- ja kannustusstipendi](https://www.kangasala.fi/hyvinvointi-ja-vapaa-aika/avustukset/liikunta/stipendit/) Stipendin kohteena ovat 10-20-vuotiaat nuoret, jotka kilpailevat juniori tai/sekä yleisessä sarjassa.

-   [Suurtapahtuma-avustukset](https://www.kangasala.fi/hyvinvointi-ja-vapaa-aika/avustukset/suurtapahtuma-avustus/) Avustus on tarkoitettu oikeuskelpoisille yhteisöille, kuten rekisteröidyille yhdistyksille, osuuskunnille, säätiöille ja yrityksille, joiden suunniteltu tapahtuma sijoittuu Kangasalle.

-   [Muut avustukset](https://www.kangasala.fi/hyvinvointi-ja-vapaa-aika/avustukset/muut-avustukset/) Hyvinvointilautakunta jakaa vuodesta avustusta hyvinvointia edistävään toimintaan. Avustusta voidaan myöntää yhteisölle, jonka toiminta edistää asukkaiden hyvinvointia ja terveyttä, kehittää asukkaiden omaa elinpiiriä, vahvistaa yhteisöllisyyttä ja aktivoi kaupunkilaisia. Hakijoina voivat olla esimerkiksi yhdistykset, säätiöt ja kyläyhdistykset.

## Nuorisotyö

Kangasalan kaupungin nuorisopalveluiden nuorisotyötä tehdään monipuolisesti ja koulujen kanssa tiiviissä yhteistyössä. Nuorisotyön palvelut on tarkoitettu kaikille alle 29-vuotiaille nuorille. Pääkohderyhmä on 13 - 17 -vuotiaat, mutta toimintaa järjestetään myös alakouluikäisille sekä täysi-ikäisille.

[Nuorten neliö - kangasalalaisille 16 -- 29 -vuotiaille nuorille tarkoitettu avoin kohtaamispaikka](https://www.kangasala.fi/tyo-ja-yrittajyys/tyollisyyspalvelut/palvelut-nuorille/nuorten-nelio/)

## Oppilas- ja opiskelijakunnat

Oppilas- ja opiskelijakuntien yhteystiedot löytyvät kunkin koulun verkkosivuilta. Kouluissa on myös muuta osallisuutta kuin oppilas- ja opiskelijakuntatoiminta. Välituntitoimintaa järjestävät oppilasryhmät, Ketu-tiimit eli kestävä tulevaisuus -tiimien ketu-agenttitoiminta, jonka myötä oppilaat kehittävät koulunsa kestävä tulevaisuus -toimintaa. Koulut tekevät vuosittain osana lukuvuosisuunnitelmaa suunnitelman oppilaiden ja huoltajien osallisuuden edistämisestä. Oppilas- ja opiskelijakuntien kanssa yhteistyötä tekee myös nuorisovaltuusto. Oppilas- ja opiskelijakunnat voivat vuosittain syksyllä osallistua nuorisovaltuuston järjestämään koulutukseen ja oppilaskunnat voivat jättää nuorisovaltuustolle aloite-ehdotuksia.

## Vanhempainyhdistykset

Kaikilla kouluilla toimii vanhempainyhdistys. Yhteystiedot löytyvät koulujen sivuilta. Vanhempainyhdistyksillä on myös kattojärjestö Kangasalan vanhemmat ry. 

Joissakin varhaiskasvatusyksiköissä on toiminnassa vanhempainyhdistyksiä tai --toimikuntia.

## Luontoretket ja ympäristötalkoot

Kaupungin ympäristönsuojelu järjestää vuosittain useita luontoretkiä. Lue lisää tapahtumista [tapahtumakalenterista](https://www.kangasala.fi/kaupunki-ja-paatoksenteko/osallistu-ja-vaikuta/tilaisuudet-ja-tapahtumat/) . Vieraslajitalkoot on järjestetty vuosittain v.2020 alkaen yhteistyössä ympäristönsuojelun ja ulkoalueiden ylläpidon kanssa). Kaupunki kannustaa kuntalaisia kesäkaudella myös omien kitkentätalkoiden järjestämiseen mm. tarjoamalla jätesäkit vieraskasvilajien keräämiseen ja hakemalla jätesäkit pois.
