# Toimintaosallisuus

Toimintaosallisuudessa kuntalainen osallistuu toimintaan elinympäristönsä kehittämiseksi, esimerkkinä siivoustalkoot.

## Asukastoiminta asukas- ja kyläyhdistyksissä

Kangasalla on aktiivista asukas- tai kyläyhdistystoimintaa. [Yhteystiedot löytyvät kaupungin verkkosivuilta.](https://www.kangasala.fi/hyvinvointi-ja-vapaa-aika/yhdistykset-ja-seurat/)

## Asukkaiden omaehtoisen toiminnan tukeminen

Kaupunki tukee asukkaiden omaehtoista toimintaa oman asuinalueen kehittämiseksi ja elävöittämiseksi.

-   [Kulttuuritoiminnan kohdeavustus](https://suomiviestit.fi/suomi.fi/lomake/60337de0475a6c2cf601e209) Hyvinvointilautakunta myöntää avustuksia yhdistysrekisterissä oleville kangasalalaisille kulttuuriyhdistyksille.

-   [Kulttuuristipendit](https://www.kangasala.fi/hyvinvointi-ja-vapaa-aika/avustukset/kulttuuri/kulttuuristipendit/) Kulttuuristipendien hakuaika on vuosittain maaliskuussa. Stipendiä voi hakea myös toisen henkilön puolesta tämän suostumuksella (asianosaisen tai huoltajan suostumus/allekirjoitus).

-   [Björkqvist-rahaston apurahat ja stipendit](https://www.kangasala.fi/hyvinvointi-ja-vapaa-aika/avustukset/kulttuuri/bjorkqvistin-rahaston-stipendit-ja-apurahat/) Björkqvist-rahastosta myönnetään apurahoja Kangasalan peruskoulusta tai toisen asteen oppilaitoksesta päättötodistuksen saaneiden hakijoiden tieteelliseen tutkimukseen tai taiteelliseen toimintaan.

-   [Nuoriso - toiminta-avustus](https://www.kangasala.fi/hyvinvointi-ja-vapaa-aika/avustukset/nuoriso/) Sivistyslautakunta avustaa nuorisojärjestöjä ja järjestäytyneitä nuorisoryhmiä vuosiavustuksella.

-   [Liikunta - toiminta-avustus](https://www.kangasala.fi/hyvinvointi-ja-vapaa-aika/avustukset/liikunta/vuosiavustus/) Hyvinvointilautakunta myöntää toiminta-avustuksia yhdistysrekisterissä oleville kangasalalaisille liikunta- ja urheiluseuroille ja yhdistyksille. Toiminta-avustusten hakuaika on vuosittain 1.-31.3.

-   [Liikunta - kohdeavustus](https://www.kangasala.fi/hyvinvointi-ja-vapaa-aika/avustukset/liikunta/kohdeavustus/) Liikunnan kohdeavustukset tulee hakea talven toiminta-ajalta 1.11.-30.4.Kohdeavustusta myönnetään ensisijaisesti yhdistysrekisterissä olevien seurojen valmentaja-, ohjaus ja toimitsijakoulutuksesta aiheutuneisiin kustannuksiin.

-   [Valmennus- ja kannustusstipendi](https://www.kangasala.fi/hyvinvointi-ja-vapaa-aika/avustukset/liikunta/stipendit/) Stipendin kohteena ovat 10-20-vuotiaat nuoret, jotka kilpailevat juniori tai/sekä yleisessä sarjassa.

## ✴️ Lähiruokatuottajien verkosto osana vapaa-ajanfoorumia [-@sec-vapaa_aika_foorumi]

[Miten toimii tällä hetkellä?]{style="color:red"}

## Nuorten neliö

[Nuorten neliö - kangasalalaisille 16 -- 29 -vuotiaille nuorille tarkoitettu avoin kohtaamispaikka](https://www.kangasala.fi/tyo-ja-yrittajyys/tyollisyyspalvelut/palvelut-nuorille/nuorten-nelio/)

## ✴️ Omaehtoisen toiminnan tukeminen

[Miten toimii tällä hetkellä? Tilavaraukset, yms.]{style="color:red"}

## Oppilaskunnat

Oppilaskuntien yhteystiedot löytyvät kunkin koulun verkkosivuilta.

## ✴️ Pop-up toiminta

[Miten toimii tällä hetkellä?]{style="color:red"}

## ✴️ Talkootoiminta

[Miten toimii tällä hetkellä?]{style="color:red"}

## ✴️ Tapahtumakumppanuudet

[Miten toimii tällä hetkellä?]{style="color:red"}

## Vanhempainyhdistykset

Kaikilla kouluilla toimii vanhempainyhdistys. Yhteystiedot löytyvät koulujen sivuilta.

## Vapaaehtoistyö

Vapaaehtoistyön keskuksena toimii Kangasalla Jalmarin Koto yhteistyössä SPR:n kanssa. Seurakunnalla on myös omaa ystäväpalvelutoimintaa sekä Kangasalla että Pälkäneellä. MLL:n paikallisyhdistys tekee vapaaehtoistyötä kangasalalaisten lasten ja lapsiperheiden hyväksi. Tukihenkilötoiminta
