# Päätösosallisuus

Päätösosallisuudessa kuntalainen osallistuu suoraan palvelujen tuottamista tai asuinaluettaan koskeviin päätöksiin.

## Aloite

Kuntalain mukaan asukkaalla sekä alueella toimivalla yhteisöllä ja säätiöllä on oikeus tehdä aloitteita kunnan toimintaa koskevissa asioissa. Kirjallisen aloitteen voi tehdä sähköisen aloitesivuston kautta [kuntalaisaloite.fi](https://www.kuntalaisaloite.fi/fi) tai toimittamalla kirjallisen aloitteen kaupungin kirjaamoon.

## Kansanäänestys

Kaupunginvaltuusto voi päättää, että kaupungille kuuluvasta asiasta toimitetaan kaupungin alueella neuvoa-antava kansanäänestys. Äänestysoikeus määräytyy samoin kuin äänioikeus kuntavaaleissa. Tulos on neuvoa-antava.

## Kaupungin vaikuttamistoimielimet

Kaupunginhallitus asettaa vaikuttamistoimielimet. Kangasalla on toiminnassa seuraavat vaikuttamistoimielimet:

-   [Asukas- ja alueneuvosto]{style="color:red"}

-   [Nuorisovaltuusto]{style="color:red"}

-   [Vammaisneuvosto]{style="color:red"}

-   [Vanhusneuvosto]{style="color:red"}

-   [Vapaa-ajantoimikunta]{style="color:red"}

## Kaupungin viralliset toimielimet

-   Kaupunginvaltuusto
-   Kaupuginhallitus
-   Lautakunnat
    -   [Keskusvaalilautakunta](https://www.kangasala.fi/kaupunki-ja-paatoksenteko/paatoksenteko/toimielimet/lautakunnat/keskusvaalilautakunta/)
    -   [Elinympäristölautakunta](https://www.kangasala.fi/kaupunki-ja-paatoksenteko/paatoksenteko/toimielimet/lautakunnat/elinvoimalautakunta/)
    -   [Sivistyslautakunta](https://www.kangasala.fi/kaupunki-ja-paatoksenteko/paatoksenteko/toimielimet/lautakunnat/sivistyslautakunta/)
    -   [Hyvinvointilautakunta](https://www.kangasala.fi/kaupunki-ja-paatoksenteko/paatoksenteko/toimielimet/lautakunnat/hyvinvointilautakunta/)
    -   [Viranomaislautakunta](https://www.kangasala.fi/kaupunki-ja-paatoksenteko/paatoksenteko/toimielimet/lautakunnat/viranomaislautakunta/)
    -   [Tarkastuslautakunta](https://www.kangasala.fi/kaupunki-ja-paatoksenteko/paatoksenteko/toimielimet/lautakunnat/tarkastuslautakunta/)
    -   [Kangasalan Vesi -liikelaitoksen johtokunta](https://www.kangasala.fi/kaupunki-ja-paatoksenteko/paatoksenteko/toimielimet/lautakunnat/kangasalan-vesi-liikelaitoksen-johtokunta/)

## Lausunto

Kangasalan kaupunki pyytää julkisilla kuulutuksilla lausuntoja eri tahoilta niin kaupunkiorganisaation sisällä kuin myös asianosaisilta, joita aina kulloinenkin aihe koskee. Lausunnot otetaan huomioon päätöksenteossa.

## Muut yhteistyöfoorumit

[Mitä muita yhteistyöfoorumeita on?]{style="color:red"}

## Muutoksenhaku

Muutoksenhaku on yksi vaikuttamiskeino. Muutoksenhaun kohteena voivat yleensä olla kaupungin viranomaisen lopulliset päätökset. Valmistelua tai täytäntöönpanoa koskeviin päätöksiin ei voi hakea muutosta.

## Äänestäminen

Äänestäminen on osallistumista ja vaikuttamista. Kuntavaalit pidetään neljän vuoden välein.
