## Toimenpiteet Kangasalla

Kangasala toimii ja kehittää aktiivisesti näitä osallisuuden muotoja. Palvelualueet toteuttavat osaltaan osallisuutta ja vuorovaikutusta strategian mukaisesti.

### Tieto-osallisuus

-   Tieto-osallisuus (Kotka, Lappeenranta)

    -   Tieto-osallisuus käsittää asukkaan oikeuden tiedon saamiseen ja tuottamiseen. Kaupungin toiminnan ja päätöksen teon tulee olla mahdollisimman avointa. Viestinnän on oltava oikea-aikaista ja ymmärrettävää. Tieto-osallisuus liittyy kuntalaisten oikeuteen saada tietoa, kuntalaisten kuulemiseen ja kyselyihin vastaamiseen.

-   Suunnitteluosallisuus,

    -   Asukas osallistuu kaupungin toiminnan suunnitteluun ja kertoo mielipiteitään. Suunnitteluosallisuuden muotoja on lukuisia kuten asukasraadit, asukas- ja kyläillat, asiakaspalaute ja -kyselyt, sähköiset osallistumiskanavat ja osallistuva budjetointi.

-   Päätöksenteko-osallisuus Asukkaalla on mahdollisuus osallistua itseä tai vaikkapa omaa asuinaluetta koskevien asioiden valmisteluun esimerkiksi toimimalla kaupungin vaikuttamistoimielimissä tai muissa kaupungin luottamustehtävissä. Myös äänestäminen suorissa vaaleissa ja osallistuminen neuvoaantavaan kansanäänestykseen ovat päätöksenteko-osallisuuden muotoja.

-   Toimintaosallisuus Toimintaosallisuus on ihmisen omaa toimintaa ja konkreettista osallistumista erilaisiin tehtäviin omassa elinympäristössä. Tällaista toimintaa voi olla esimerkiksi osallistuminen erilaisiin tapahtumiin, vapaaehtoistoimintaan, talkootyöhön, yhdistystoimintaan tai kohtaamispaikkatoimintaan.

-   Palautteet ja kyselyt

-   Lausunnot ja aloitteet

-   Äänestykset

-   Osallistava budjetointi (myös Hamina)

-   Asukasraadit

-   Asiakaskehittäjät

-   Vaikuttamistoimielimet (parlamentit, foorumit)

-   Vanhusneuvosto

-   Vammaisneuvosto

-   Nuorisovaltuusto

-   Nuorten kouluruokaraati (Hamina)

-   Facebook (Hamina)

-   Palvelumuotoilu (Hamina)

-   Yhdyspintojen tunnistaminen (Hamina)

-   Avustukset

-   Jalkautuva asukastyö (yleisötilaisuudet)

-   Kuulemistilaisuudet

-   Talkoot, roskien keräys (Hamina)

-   Vapaaehtoistyö (Hamina)

-   Osallisuus- ja hyvinvointikysely (Hamina)

-   Ideakioski (Hyvinkää)

-   Viestitään avoimesti ja aktiivisesti (Akaa)

-   Osallisuustyökalu (henkilöstölle ohje osallistaa - Hyvinkää)

## Tavoite

-   Äänestysaktiivisuus lisääntyy (Kauhajoki)

-   Kaupungin sisäinen/ulkoinen viestintäohje on laadittu (Kauhajoki)

-   Viestinnän vuosikello (Lapinlahti)

-   Viestinnän monikanavaisuus (FB, Insta, Whatsapp, Sähköposti, Tiktok), Lapinlahti, Orivesi, Tampere

-   Viestinnän kuntalaisraati, näkemyksiä viestinnän kehittämiseen (Orivesi)

-   Paikallislehti (Pirkkala)

-   Julkiset asiakirjat (Pirkkala)

-   Valtuustokokousten verkkolähetykset (Pirkkala)

-   Vanhempainyhdistykset (Pirkkala)

-   Seuraparlamentti (Pirkkala)

-   osallistuvavantaa.fi

-   Perheliikuntaverkosto (Pirkkala)

-   Kertaluonteiset pop-up raadit palvelujen kehitämiseen (Pirkkala)

-   Otakantaa.fi, Haloo Pirkkala sovellus palautekanavana

-   Ennakkovaikutusten arviointi (Pirkkala), EVA-menettlyn selkeyttäminen

-   Järjestöfoorumi, viestinnän tukeminen ja avustusprosessin kehittäminen (Lapinlahti)

-   Kumppanuuspöytä yhteistyössä kolmanne sektorin kanssa, maakunnan ja Essoten (Mikkeli, Orivesi)

-   Vuosittainen järjestö-tet (Lapinlahti)

-   Kyselyt kuntalaisille (Lapinlahti)

-   Osallisuuden vuosikello (Lapinlahti)

-   HappyOrNot (Orivesi)

-   Kaavakävelyt (Orivesi)

-   Yrittäjien aamukahvit (Orivesi)

-   Yritysvaikutusten arviointi (Orivesi)

-   Yritysvierailut (Orivesi)

-   Yrittäjäkyselyt (Orivesi)

-   Vikailmoitukset (Orivesi)

-   Kaupungin toiminnan vuosikello (Kauhajoki)

-   Kaupungin palvelukartta (Kauhajoki)

-   Asukkaille tarjotaan koulutusta osallisuudesta (Kauhajoki)

-   Avoimet matalankynnyksen kohtaamispaikat (Mikkeli)

-   Omaehtoisen toiminnan mahdollistaminen (tilavarausten helpottaminen kuntalaisille), Mikkeli

-   Avoimen hallinnon edistäminen, kerrokantasi.hel.fi tyyppinen palvelu (Mikkeli)

-   Monikulttuurisuuden hiominen (Kauhajoki)

-   Vaikuttajatoimielinten yhteistyön lisääminen (Kauhajoki)

-   Mökkilaiturilla-sovellus - https://laiturilla.fi/mobiilisti (Etelä-Savo, hanke)

-   Laiturilla-foorumi (Etelä-Savo), 2-3h mittaisia, alustuksia, yrittäjiä, mökkiläisiä, päättäjiä

-   Mökkiläisfoorumi (Sisäasianministeriö, Viitasaari https://viitasaari.fi/kaupunki-ja-hallinto/toimikunnat-ja-tyoryhmat/mokkilaisfoorumi/, Parainen)

-   Mökkiläistoimikunta (Sisäasianministeriö, Kustavi https://kustavi.fi/kunta-ja-hallinto/paatoksenteko/lautakunnat-ja-jaostot/mokkilaistoimikunta/, Kuhmno https://www.kuhmo.fi/asuminen-ja-ymparisto/asuinymparistomme/mokki-kuhmo/)

-   Lähiruokatuottajien verkosto osana mökkiläisfoorumia (Norja)

-   Mökkiläiset toimivat alueen lähettiläinä matkamessuilla (Norja) https://www.valdres.com/

-   Asukasfoorumien määrä (Kauhajoki)

-   Säännölliset turvallisuuskävelyt asukastaajamissa (Kauhajoki)

-   Maankäytön ja kaavoituksen tiedotustilaisuduet (Kauhajoki)

-   Lapsivaikutusten arviointi (Kauhajoki)

-   Lasten harrastustoiminnan järjestäjien ja kaupungin yhteistyötilaisuudet (Kauhajoki)

-   Varhaiskasvatuksen asiakasraati

-   Esteettömyystyöryhmä Esteettömien tilojen esite (Kotka)

-   Saaristotoimikunta (Kotka)

-   Monikulttuuristen asioiden käsittelemistä edistävä toimielin (Kotka)

-   Kohderyhmien määrittely alueittain (Vantaa)
